webSys/dbweb/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

mail = Mail()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'user.signin'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Register all the filter.
    from .util import filter_blueprint
    app.register_blueprint(filter_blueprint)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .user import user as user_blueprint
    app.register_blueprint(user_blueprint, url_prefix='/user')
    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')
    # from .group import group as group_blueprint
    # app.register_blueprint(group_blueprint, url_prefix='/group')
    from .category import category as category_blueprint
    app.register_blueprint(category_blueprint, url_prefix='/category')
    from .article import article as article_blueprint
    app.register_blueprint(article_blueprint, url_prefix='/article')
    from .stock import stock as stock_blueprint
    app.register_blueprint(stock_blueprint, url_prefix='/stock')
    from .search import search as search_blueprint
    app.register_blueprint(search_blueprint, url_prefix='/search')
    from .algo import algo as algo_blueprint
    app.register_blueprint(algo_blueprint, url_prefix='/algo')

    return app

webSys/dbweb/admin/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
admin = Blueprint('admin', __name__)
from . import views, system_views

webSys/dbweb/admin/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from flask import render_template, request, redirect, url_for, abort, jsonify
from flask_login import login_user, current_user, login_required, logout_user
from datetime import datetime
from ..user.authorize import admin_login, system_login
from ..util.user_manage import is_admin_user
from . import admin
from ..models import User, Article, Category
from .. import db
from flask_babel import gettext


@admin.route('/auth/', methods=["GET", "POST"])
def auth():
    if request.method == "GET":
        return render_template('admin/auth.html', title=gettext("Admin Auth"))

    elif request.method == "POST":
        _form = request.form
        u = User.query.filter_by(email=_form['email']).first()
        if u and u.verify_password(_form['password']) and (u.permissions == 0):
            login_user(u)
            u.last_login = datetime.now()
            db.session.commit()
            if u.permissions == 0:
                return redirect(url_for('admin.system'))
        else:
            message = gettext('Invalid username or password.')
            return render_template('admin/auth.html', title="Administrator",
                                   form=_form,
                                   message=message)


@admin.route('/logout/')
@admin_login
def logout():
    logout_user()
    return redirect(request.args.get('next') or request.referrer or url_for('admin.auth'))


@admin.route('/system/')
@system_login
def system():
    user_cnt = User.query.count()
    article_cnt = Article.query.count()
    category_cnt = Category.query.count()
    return render_template("admin/system.html",
                           user_cnt=user_cnt,
                           article_cnt=article_cnt,
                           group_cnt=category_cnt,
                           title="System Management")

webSys/dbweb/algo/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
algo = Blueprint('algo', __name__)
from . import views

webSys/dbweb/algo/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from flask import render_template, request, redirect, url_for, abort, jsonify, current_app
from flask_login import login_user, logout_user, current_user, login_required
from flask_babel import gettext
from datetime import datetime
import os

from ..util.run_backtest import run_strategy
from ..util.text_process import python
from ..util.get_backtest_result import get_backtest_result
from . import algo
from ..models import Strategy
from .. import db


@algo.route('/')
@login_required
def index():
    strategy = current_user.strategy
    return render_template('algo/index.html',
                           title=gettext('Algorithm'),
                           strategy=strategy)


# 创建策略
@algo.route('/new/', methods=['POST', 'GET'])
@login_required
def strategy_new():
    if request.method == 'GET':
        return render_template('algo/edit.html',
                               title=gettext('Algorithm'))
    if request.method == 'POST':
        name = request.form['name']
        # code = request.form['content']
        codePath = os.path.join(current_app.config['UPLOAD_FOLDER'], 'code', 'stTemplate.py')
        code = open(codePath, 'rb').read()
        new_strategy = Strategy(name=name, code=code, user_id=current_user.id)
        db.session.commit()

        # 更新用户对应的策略
        current_user.strategy.append(new_strategy)
        current_user.strategy_num += 1
        db.session.commit()
        return redirect(url_for('algo.strategy_edit',
                                sid=new_strategy.id,
                                strategy=new_strategy))


# 策略编辑
@algo.route('/edit/<int:sid>/')
@login_required
def strategy_edit(sid):
    cur_strategy = Strategy.query.filter_by(id=sid).first_or_404()
    if current_user.id != cur_strategy.user_id:
        abort(403)
    else:
        return render_template('algo/edit.html',
                               title=cur_strategy.name,
                               strategy=cur_strategy)


# 策略更新
@algo.route('/update/<int:sid>', methods=['POST', 'GET'])
@login_required
def strategy_update(sid):
    cur_strategy = Strategy.query.filter_by(id=sid).first_or_404()
    if current_user.id != cur_strategy.user_id:
        abort(403)
    else:
        name = request.form["name"]
        code = request.form['code']
        cur_strategy.name = name
        cur_strategy.code = code

        cur_strategy.modified_time = datetime.now()
        db.session.commit()

        return jsonify(name=name, code=code)


# 策略删除
@algo.route('/del/', methods=['POST', 'GET'])
@login_required
def strategy_delete():
    cur_strategy = Strategy.query.filter_by(id=request.form['id']).first_or_404()
    db.session.delete(cur_strategy)
    db.session.commit()
    return jsonify(status="success", del_strategy_id=cur_strategy.id)


# 策略批量删除
@algo.route('/batchDel/', methods=['POST', 'GET'])
@login_required
def strategy_batch_delete():
    idx = request.form.getlist('id[]')
    for x in idx:
        curr_strategy = Strategy.query.filter_by(id=x).first_or_404()
        db.session.delete(curr_strategy)
    db.session.commit()
    return jsonify(status='success')


# 策略运行
@algo.route('/run/<int:sid>/', methods=['POST', 'GET'])
@login_required
def strategy_run(sid):
    start_date = request.form['start-date']
    end_date = request.form['end-date']
    print("&&&&&&&:", start_date, "::", end_date)
    cur_strategy = Strategy.query.filter_by(id=sid).first_or_404()
    ## save as tmp .py file
    code_dir = os.path.join(current_app.config['UPLOAD_FOLDER'], 'code')
    code_path = os.path.join(code_dir, "%d.py" % cur_strategy.id)
    print(code_path)

    with open(code_path, "w") as f:
        f.write(cur_strategy.code)

    result = run_strategy(start_date, end_date)

    print(result, "DONE!")

    picklePath = os.path.join(current_app.config['UPLOAD_FOLDER'], 'pickle')
    data_result = get_backtest_result(picklePath)

    senddata = {"data_result": data_result}
    return jsonify(senddata)

webSys/dbweb/article/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
article = Blueprint('article', __name__)
from . import views

webSys/dbweb/article/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import render_template, abort, request, redirect, url_for
from . import article
from ..models import Article
from flask_babel import gettext
from .. import db


@article.route('/')
def index():
    article_list = Article.query.all()
    return render_template('article/index.html', title="Notices", article_list=article_list)


@article.route('/<int:article_id>')
def detail(article_id):
    detail_article = Article.query.filter_by(id=article_id).first()
    detail_article.visit_num += 1
    db.session.commit()
    return render_template('article/detail.html',
                           title=detail_article.title[:10],
                           article=detail_article)

webSys/dbweb/category/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
category = Blueprint('category', __name__)
from . import views

webSys/dbweb/category/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import render_template, abort, request, redirect, url_for, jsonify
from flask_login import current_user, login_required
from flask_babel import gettext
from datetime import datetime
from . import category
from ..models import Topic, Post
from ..util.text_process import add_user_links_in_content
from .. import db

# 社区首页
@category.route('/all/')
def all():
    all_topic = Topic.query.all()
    return render_template('category/all.html',
                           title=gettext('All'),
                           all_topic=all_topic,
                           cate='all')

@category.route('/research/')
def research():
    all_topic = Topic.query.filter_by(cat_type=1).all()
    return render_template('category/research.html',
                           title=gettext('Research'),
                           all_topic=all_topic)

@category.route('/study/')
def study():
    all_topic = Topic.query.filter_by(cat_type=2).all()
    return render_template('category/study.html',
                           title=gettext('Study'),
                           all_topic=all_topic)

@category.route('/question/')
def question():
    all_topic = Topic.query.filter_by(cat_type=3).all()
    return render_template('category/question.html',
                           title=gettext('Question'),
                           all_topic=all_topic)

# 话题的详细页面
@category.route('/topic/<int:tid>/')
def topic_view(tid):
    cur_topic = Topic.query.filter_by(id=tid).first_or_404()
    cur_topic.visit_num += 1
    db.session.commit()
    return render_template('category/topic_detail.html',
                           title=cur_topic.title,
                           topic=cur_topic)

@category.route('/topic/new/', methods=['GET', 'POST'])
@login_required
def topic_new():
    if request.method == 'GET':
        print("GET+++++++++++++++++++++")
        return render_template('category/topic_new.html',
                               title='New Topic')
    elif request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        cate_type = request.form['cate-type']
        new_topic = Topic(current_user.id, title, content, cate_type)
        db.session.commit()

        # 更新用户和专栏对应的话题
        current_user.topics.append(new_topic)
        current_user.topic_num += 1
        db.session.commit()
        return redirect(url_for('category.topic_view', tid=new_topic.id))

# 话题编辑页面
@category.route('/topic/edit/<int:tid>')
@login_required
def topic_edit(tid):
    cur_topic = Topic.query.filter_by(id=tid).first_or_404()
    if current_user.id != cur_topic.user_id:
        abort(403)
    else:
        return render_template('category/topic_edit.html',
                               title=cur_topic.title,
                               topic=cur_topic)

# 更新话题
@category.route('/topic/update/<int:tid>/', methods=['POST'])
@login_required
def topic_update(tid):
    cur_topic = Topic.query.filter_by(id=tid).first_or_404()
    if current_user.id != cur_topic.user_id:
        abort(403)
    else:
        content = request.form['content']
        title = request.form['title']
        cur_topic.title = title
        cur_topic.content = content
        cur_topic.updatedTime = datetime.now()
        db.session.commit()

        return redirect(url_for('category.topic_view', tid=cur_topic.id))

# 在话题下发表评论
@category.route('/topic/<int:tid>/comment/create/', methods=['POST'])
@login_required
def create_post(tid):
    cur_topic = Topic.query.filter_by(id=tid).first_or_404()
    post_content = request.form['content']
    post_content = add_user_links_in_content(post_content)

    new_post = Post(current_user.id, content=post_content)
    cur_topic.posts.append(new_post)
    cur_topic.post_num += 1

    current_user.post_num += 1
    db.session.add(new_post)
    db.session.commit()

    new_post_html = render_template('category/widget_post_detail.html',
                                    p=new_post,
                                    index=cur_topic.post_num)

    return jsonify(post_html=new_post_html,
                   post_cnt=cur_topic.post_num)

webSys/dbweb/group/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
group = Blueprint('group', __name__)
from . import views

webSys/dbweb/main/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
main = Blueprint('main', __name__)
from . import views

webSys/dbweb/main/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from flask import render_template
from . import main
from flask_babel import gettext
from ..models import Article, Stock, News, Follow_Stock
import tushare as ts, json
import datetime
from ..util.get_yahoo_news import getLatestNews
from flask_login import login_required, current_user


@main.route('/')
def index():
    whole_indicators = json.loads(ts.get_index()[:4].to_json(orient='records'))

    getLatestNews()
    whole_news = News.query.order_by(News.time.desc()).limit(7)
    # 站点公告
    notice = Article.query.order_by(Article.updated_time.desc()).limit(7)

    dates = datetime.datetime.now()
    week = datetime.datetime.now().weekday()
    if week in [5, 6]:
        days = 4 - week
        dates = dates + datetime.timedelta(days=days)
    dates = dates.strftime('%Y-%m-%d')

    recommend_stocks = Stock.query.filter(Stock.code != 'ALL').limit(8).all()
    if current_user.is_authenticated:
        for i in range(len(recommend_stocks)):
            if Follow_Stock.query.filter_by(user_id=current_user.id,
                                            stock_id=recommend_stocks[i].code).first() is not None:
                recommend_stocks[i].flag = True
            else:
                recommend_stocks[i].flag = False

    return render_template('main/index.html',
                           whole_indicators=whole_indicators,
                           news=whole_news,
                           notices=notice,
                           dates=dates,
                           stocks=recommend_stocks)


@main.app_errorhandler(404)
def page_404(err):
    return render_template('404.html', title='404'), 404


@main.app_errorhandler(403)
def page_403(err):
    return render_template('403.html', title='403'), 403


@main.app_errorhandler(500)
def page_500(err):
    return render_template('500.html', title='500'), 500

webSys/dbweb/search/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
search = Blueprint('search', __name__)
from . import views

webSys/dbweb/search/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from flask import render_template, request, redirect, url_for, current_app
from . import search
from flask_babel import gettext
import tushare as ts, json
import datetime

@search.route('/')
def index():
    stockcode = request.args.get('q')
    with current_app.open_resource('stock.json') as f:
        stock_dic = json.loads(f.read())

    if stockcode in stock_dic:
        return redirect(url_for('stock.stock_view', code=stockcode))
    else:
        return render_template('404.html', title='404'), 404

@search.app_errorhandler(404)
def page_404(err):
    return render_template('404.html', title='404'), 404


@search.app_errorhandler(403)
def page_403(err):
    return render_template('403.html', title='403'), 403


@search.app_errorhandler(500)
def page_500(err):
    return render_template('500.html', title='500'), 500

webSys/dbweb/stock/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
stock = Blueprint('stock', __name__)
from . import views

webSys/dbweb/user/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-


from flask import Blueprint
user = Blueprint('user', __name__)
from . import views

webSys/dbweb/templates/category/all.html
{% extends 'base.html' %}

{% block content %}
    <div id="content-container" class="container">
        <ol class="breadcrumb breadcrumb-o" style="margin-top:-18px">
            <li><a href="/">{{ _('Index') }}</a></li>
            <li class="active"><a href="{{ url_for('category.all') }}">{{ _('All') }}</a></li>
        </ol>
        <div class="row">
            <div class="col-md-9">
                <div class="panel panel-default">
                    <ul class="nav nav-tabs" id="topic-nav">
                        <li role="presentation" class="active">
                            <a href="{{ url_for('category.all') }}" aria-controls="all" role="tab"
                               data-toggle="tab">{{ _('All') }}</a>
                        </li>
                        <li role="presentation">
                            <a href="{{ url_for('category.research') }}" aria-controls="research" role="tab"
                               data-toggle="tab">{{ _('Research') }}</a>
                        </li>
                        <li role="presentation">
                            <a href="{{ url_for('category.study') }}" aria-controls="study" role="tab"
                               data-toggle="tab">{{ _('Study') }}</a>
                        </li>
                        <li role="presentation">
                            <a href="{{ url_for('category.question') }}" aria-controls="question" role="tab"
                               data-toggle="tab">{{ _('Question') }}</a>
                        </li>
                    </ul>

                    {% with topics = all_topic %}
                        {% include 'category/widget_topic_list.html' %}
                    {% endwith %}
                </div>
            </div>
            {% include 'category/widget_category_aside.html' %}
        </div>
    </div>

{% endblock %}
{% block footer_ext %}
    <script src="{{ url_for('static',filename='js/jquery-scrolltofixed-min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#topic-nav').scrollToFixed();
        });
    </script>
{% endblock %}

webSys/dbweb/templates/category/question.html
{% extends 'base.html' %}

{% block content %}
    <div id="content-container" class="container">
        <ol class="breadcrumb breadcrumb-o" style="margin-top:-18px">
            <li><a href="/">{{ _('Index') }}</a></li>
            <li class="active"><a href="{{ url_for('category.all') }}">{{ _('All') }}</a></li>
        </ol>
       <div class="row">
            <div class="col-md-9">
                <div class="panel panel-default">

                            <ul class="nav nav-tabs" id="topic-nav">
                                <li role="presentation">
                                    <a href="{{ url_for('category.all') }}" aria-controls="all" role="tab"
                                       data-toggle="tab">{{ _('All') }}</a>
                                </li>
                                <li role="presentation">
                                    <a href="{{ url_for('category.research') }}" aria-controls="research" role="tab"
                                       data-toggle="tab">{{ _('Research') }}</a>
                                </li>
                                <li role="presentation">
                                    <a href="{{ url_for('category.study') }}" aria-controls="study" role="tab"
                                       data-toggle="tab">{{ _('Study') }}</a>
                                </li>
                                <li role="presentation" class="active">
                                    <a href="{{ url_for('category.question') }}" aria-controls="question" role="tab"
                                       data-toggle="tab">{{ _('Question') }}</a>
                                </li>
                            </ul>

                    {% with topics = all_topic %}
                        {% include 'category/widget_topic_list.html' %}
                    {% endwith %}
                </div>
            </div>
            {% include 'category/widget_category_aside.html' %}
       </div>
    </div>

{% endblock %}
{% block footer_ext %}
    <script src="{{ url_for('static',filename='js/jquery-scrolltofixed-min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#topic-nav').scrollToFixed();
        });
    </script>
{% endblock %}

webSys/dbweb/templates/category/research.html
{% extends 'base.html' %}

{% block content %}
    <div id="content-container" class="container">
        <ol class="breadcrumb breadcrumb-o" style="margin-top:-18px">
            <li><a href="/">{{ _('Index') }}</a></li>
            <li class="active"><a href="{{ url_for('category.all') }}">{{ _('All') }}</a></li>
        </ol>
        <div class="row">
            <div class="col-md-9">
                <div class="panel panel-default">

                            <ul class="nav nav-tabs" id="topic-nav">
                                <li role="presentation">
                                    <a href="{{ url_for('category.all') }}" aria-controls="all" role="tab"
                                       data-toggle="tab">{{ _('All') }}</a>
                                </li>
                                <li role="presentation" class="active">
                                    <a href="{{ url_for('category.research') }}" aria-controls="research" role="tab"
                                       data-toggle="tab">{{ _('Research') }}</a>
                                </li>
                                <li role="presentation">
                                    <a href="{{ url_for('category.study') }}" aria-controls="study" role="tab"
                                       data-toggle="tab">{{ _('Study') }}</a>
                                </li>
                                <li role="presentation">
                                    <a href="{{ url_for('category.question') }}" aria-controls="question" role="tab"
                                       data-toggle="tab">{{ _('Question') }}</a>
                                </li>
                            </ul>

                    {% with topics = all_topic %}
                        {% include 'category/widget_topic_list.html' %}
                    {% endwith %}
                </div>
            </div>
            {% include 'category/widget_category_aside.html' %}
        </div>
    </div>

{% endblock %}
{% block footer_ext %}
    <script src="{{ url_for('static',filename='js/jquery-scrolltofixed-min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#topic-nav').scrollToFixed();
        });
    </script>
{% endblock %}

webSys/dbweb/templates/category/study.html
{% extends 'base.html' %}

{% block content %}
    <div id="content-container" class="container">
        <ol class="breadcrumb breadcrumb-o" style="margin-top:-18px">
            <li><a href="/">{{ _('Index') }}</a></li>
            <li class="active"><a href="{{ url_for('category.all') }}">{{ _('All') }}</a></li>
        </ol>
        <div class="row">
            <div class="col-md-9">
                <div class="panel panel-default">

                            <ul class="nav nav-tabs" id="topic-nav">
                                <li role="presentation">
                                    <a href="{{ url_for('category.all') }}" aria-controls="all" role="tab"
                                       data-toggle="tab">{{ _('All') }}</a>
                                </li>
                                <li role="presentation">
                                    <a href="{{ url_for('category.research') }}" aria-controls="research" role="tab"
                                       data-toggle="tab">{{ _('Research') }}</a>
                                </li>
                                <li role="presentation" class="active">
                                    <a href="{{ url_for('category.study') }}" aria-controls="study" role="tab"
                                       data-toggle="tab">{{ _('Study') }}</a>
                                </li>
                                <li role="presentation">
                                    <a href="{{ url_for('category.question') }}" aria-controls="question" role="tab"
                                       data-toggle="tab">{{ _('Question') }}</a>
                                </li>
                            </ul>

                    {% with topics = all_topic %}
                        {% include 'category/widget_topic_list.html' %}
                    {% endwith %}
                </div>
            </div>
            {% include 'category/widget_category_aside.html' %}
        </div>
    </div>

{% endblock %}
{% block footer_ext %}
    <script src="{{ url_for('static',filename='js/jquery-scrolltofixed-min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('#topic-nav').scrollToFixed();
        });
    </script>
{% endblock %}

webSys/dbweb/templates/category/topic_edit.html
{% extends 'base.html' %}

{% block header_ext %}
    <link href="{{ url_for('static', filename='css/simplemde.min.css') }}" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/simplemde.min.js') }}"></script>
{% endblock %}

{% block content %}
    <div id="content-container" class="container">
        <ol class="breadcrumb breadcrumb-o" style="margin-top:-18px">
            <li><a href="/">{{ _('Index') }}</a></li>
            <li><a href="{{ url_for('category.all') }}">{{ _('ALL') }}</a></li>

            <li class="active">
                <a href="{{ url_for('category.topic_view', tid=topic.id) }}">{{ topic.title | truncate(20) }}</a>
            </li>
        </ol>

        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{{ url_for('category.topic_update', tid=topic.id) }}" method="POST" onsubmit="validateForm()">
                        <div class="form-group">
                            <label>{{ _('Title') }}</label>
                            <input type="text" class="form-control" name='title' value="{{ topic.title }}"
                                   required><br/>
                        </div>

                        <div class="form-group">
                            <label>{{ _('Content') }}</label>
                            <textarea name="content" data-provide="markdown"
                                      id="target-editor" rows="20">{{ topic.content }}</textarea>
                        </div>

                        <div class="form-submit text-right">
                            <input class='btn btn-success' id='submit' type='submit'>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_ext %}

    <script>
        var simplemde = new SimpleMDE({
            element: document.getElementById("target-editor"),
            autosave: true,
            showIcons: ["code", "table"],
            tabSize: 4,
        });

        function validateForm() {
            var x = simplemde.value();
            if (x == null || x == "") {
                alert("Please enter topic");
                return false;
            }
        }
    </script>
{% endblock %}

webSys/dbweb/templates/category/topic_new.html
{% extends 'base.html' %}

{% block header_ext %}
    <link href="{{ url_for('static', filename='css/simplemde.min.css') }}" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/simplemde.min.js') }}"></script>
{% endblock %}

{% block content %}
    <div id="content-container" class="container">
        <ol class="breadcrumb breadcrumb-o" style="margin-top:-18px">
            <li><a href="/">{{ _('Index') }}</a></li>
            <li><a href="{{ url_for('category.all') }}">{{ _('All') }}</a></li>

        </ol>

        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{{ url_for('category.topic_new') }}" method="POST" onsubmit="validateForm()">
                        <div class="form-group">
                            <label>{{ _('Title') }}</label>
                            <input type="text" class="form-control" name='title' required><br/>
                        </div>
                        <div class="form-group">
                            <label>{{ _('Category Type') }}</label>
                            <select class="form-control" id="cate-type" name="cate-type" required>
                                <option value="1">{{ _('Research') }}</option>
                                <option value="2">{{ _('Study') }}</option>
                                <option value="3">{{ _('Question') }}</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>{{ _('Content') }}</label>
                            <textarea name="content" data-provide="markdown"
                                      id="target-editor" rows="20"></textarea>
                        </div>

                        <div class="form-submit text-right">
                            <input class='btn btn-success' id='submit' type='submit'>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_ext %}
    <script>
        var simplemde = new SimpleMDE({
            element: document.getElementById("target-editor"),
            autosave: true,
            showIcons: ["code", "table"],
            tabSize: 4,
        });

        function validateForm() {
            var x = simplemde.value();
            if (x == null || x == "") {
                alert("Please enter topic");
                return false;
            }
        }
    </script>
{% endblock %}

{# group #}